### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by dingsboms** [scheb/sound-to-light-osc#6]
python beatDetector.py
Using default input device: Line (ZOOM L-20 Audio)
Traceback (most recent call last):
  File "C:\Users\richa\Downloads\sound-to-light-osc-main\sound-to-light-osc-main\bpm.py", line 85, in analyze_audio
    self.track_intensity(y_avg)
  File "C:\Users\richa\Downloads\sound-to-light-osc-main\sound-to-light-osc-main\bpm.py", line 142, in track_intensity
    self.input_recorder.beatDetector.ui.display_input_intensity(level*100/self.max_volume)
  File "C:\Users\richa\Downloads\sound-to-light-osc-main\sound-to-light-osc-main\ui.py", line 123, in display_input_intensity
    self.input_intensity.setValue(level)
TypeError: setValue(self, int): argument 1 has unexpected type 'numpy.float64'

Can't figure out what the problem is

**Comment by dingsboms** [comment]
Solved it by running it with python3.9 instead of python 3.10
